---
source: crates/ruff_linter/src/rules/flake8_pytest_style/mod.rs
---
PT027 [*] Use `pytest.raises` instead of unittest-style `assertRaises`
 --> PT027_0.py:6:14
  |
4 | class Test(unittest.TestCase):
5 |     def test_errors(self):
6 |         with self.assertRaises(ValueError):
  |              ^^^^^^^^^^^^^^^^^
7 |             raise ValueError
8 |         with self.assertRaises(expected_exception=ValueError):
  |
help: Replace `assertRaises` with `pytest.raises`
1  | import unittest
2  + import pytest
3  | 
4  | 
5  | class Test(unittest.TestCase):
6  |     def test_errors(self):
   -         with self.assertRaises(ValueError):
7  +         with pytest.raises(ValueError):
8  |             raise ValueError
9  |         with self.assertRaises(expected_exception=ValueError):
10 |             raise ValueError
note: This is an unsafe fix and may remove comments or change runtime behavior

PT027 [*] Use `pytest.raises` instead of unittest-style `assertRaises`
 --> PT027_0.py:8:14
  |
6 |         with self.assertRaises(ValueError):
7 |             raise ValueError
8 |         with self.assertRaises(expected_exception=ValueError):
  |              ^^^^^^^^^^^^^^^^^
9 |             raise ValueError
  |
help: Replace `assertRaises` with `pytest.raises`
1  | import unittest
2  + import pytest
3  | 
4  | 
5  | class Test(unittest.TestCase):
6  |     def test_errors(self):
7  |         with self.assertRaises(ValueError):
8  |             raise ValueError
   -         with self.assertRaises(expected_exception=ValueError):
9  +         with pytest.raises(ValueError):
10 |             raise ValueError
11 | 
12 |         with self.failUnlessRaises(ValueError):
note: This is an unsafe fix and may remove comments or change runtime behavior

PT027 [*] Use `pytest.raises` instead of unittest-style `failUnlessRaises`
  --> PT027_0.py:11:14
   |
 9 |             raise ValueError
10 |
11 |         with self.failUnlessRaises(ValueError):
   |              ^^^^^^^^^^^^^^^^^^^^^
12 |             raise ValueError
   |
help: Replace `failUnlessRaises` with `pytest.raises`
1  | import unittest
2  + import pytest
3  | 
4  | 
5  | class Test(unittest.TestCase):
--------------------------------------------------------------------------------
9  |         with self.assertRaises(expected_exception=ValueError):
10 |             raise ValueError
11 | 
   -         with self.failUnlessRaises(ValueError):
12 +         with pytest.raises(ValueError):
13 |             raise ValueError
14 | 
15 |         with self.assertRaisesRegex(ValueError, "test"):
note: This is an unsafe fix and may remove comments or change runtime behavior

PT027 [*] Use `pytest.raises` instead of unittest-style `assertRaisesRegex`
  --> PT027_0.py:14:14
   |
12 |             raise ValueError
13 |
14 |         with self.assertRaisesRegex(ValueError, "test"):
   |              ^^^^^^^^^^^^^^^^^^^^^^
15 |             raise ValueError("test")
   |
help: Replace `assertRaisesRegex` with `pytest.raises`
1  | import unittest
2  + import pytest
3  | 
4  | 
5  | class Test(unittest.TestCase):
--------------------------------------------------------------------------------
12 |         with self.failUnlessRaises(ValueError):
13 |             raise ValueError
14 | 
   -         with self.assertRaisesRegex(ValueError, "test"):
15 +         with pytest.raises(ValueError, match="test"):
16 |             raise ValueError("test")
17 | 
18 |         with self.assertRaisesRegex(ValueError, expected_regex="test"):
note: This is an unsafe fix and may remove comments or change runtime behavior

PT027 [*] Use `pytest.raises` instead of unittest-style `assertRaisesRegex`
  --> PT027_0.py:17:14
   |
15 |             raise ValueError("test")
16 |
17 |         with self.assertRaisesRegex(ValueError, expected_regex="test"):
   |              ^^^^^^^^^^^^^^^^^^^^^^
18 |             raise ValueError("test")
   |
help: Replace `assertRaisesRegex` with `pytest.raises`
1  | import unittest
2  + import pytest
3  | 
4  | 
5  | class Test(unittest.TestCase):
--------------------------------------------------------------------------------
15 |         with self.assertRaisesRegex(ValueError, "test"):
16 |             raise ValueError("test")
17 | 
   -         with self.assertRaisesRegex(ValueError, expected_regex="test"):
18 +         with pytest.raises(ValueError, match="test"):
19 |             raise ValueError("test")
20 | 
21 |         with self.assertRaisesRegex(
note: This is an unsafe fix and may remove comments or change runtime behavior

PT027 [*] Use `pytest.raises` instead of unittest-style `assertRaisesRegex`
  --> PT027_0.py:20:14
   |
18 |             raise ValueError("test")
19 |
20 |         with self.assertRaisesRegex(
   |              ^^^^^^^^^^^^^^^^^^^^^^
21 |             expected_exception=ValueError, expected_regex="test"
22 |         ):
   |
help: Replace `assertRaisesRegex` with `pytest.raises`
1  | import unittest
2  + import pytest
3  | 
4  | 
5  | class Test(unittest.TestCase):
--------------------------------------------------------------------------------
18 |         with self.assertRaisesRegex(ValueError, expected_regex="test"):
19 |             raise ValueError("test")
20 | 
   -         with self.assertRaisesRegex(
   -             expected_exception=ValueError, expected_regex="test"
   -         ):
21 +         with pytest.raises(ValueError, match="test"):
22 |             raise ValueError("test")
23 | 
24 |         with self.assertRaisesRegex(
note: This is an unsafe fix and may remove comments or change runtime behavior

PT027 [*] Use `pytest.raises` instead of unittest-style `assertRaisesRegex`
  --> PT027_0.py:25:14
   |
23 |             raise ValueError("test")
24 |
25 |         with self.assertRaisesRegex(
   |              ^^^^^^^^^^^^^^^^^^^^^^
26 |             expected_regex="test", expected_exception=ValueError
27 |         ):
   |
help: Replace `assertRaisesRegex` with `pytest.raises`
1  | import unittest
2  + import pytest
3  | 
4  | 
5  | class Test(unittest.TestCase):
--------------------------------------------------------------------------------
23 |         ):
24 |             raise ValueError("test")
25 | 
   -         with self.assertRaisesRegex(
   -             expected_regex="test", expected_exception=ValueError
   -         ):
26 +         with pytest.raises(ValueError, match="test"):
27 |             raise ValueError("test")
28 | 
29 |         with self.assertRaisesRegexp(ValueError, "test"):
note: This is an unsafe fix and may remove comments or change runtime behavior

PT027 [*] Use `pytest.raises` instead of unittest-style `assertRaisesRegexp`
  --> PT027_0.py:30:14
   |
28 |             raise ValueError("test")
29 |
30 |         with self.assertRaisesRegexp(ValueError, "test"):
   |              ^^^^^^^^^^^^^^^^^^^^^^^
31 |             raise ValueError("test")
   |
help: Replace `assertRaisesRegexp` with `pytest.raises`
1  | import unittest
2  + import pytest
3  | 
4  | 
5  | class Test(unittest.TestCase):
--------------------------------------------------------------------------------
28 |         ):
29 |             raise ValueError("test")
30 | 
   -         with self.assertRaisesRegexp(ValueError, "test"):
31 +         with pytest.raises(ValueError, match="test"):
32 |             raise ValueError("test")
33 | 
34 |     def test_unfixable_errors(self):
note: This is an unsafe fix and may remove comments or change runtime behavior

PT027 Use `pytest.raises` instead of unittest-style `assertRaises`
  --> PT027_0.py:34:14
   |
33 |     def test_unfixable_errors(self):
34 |         with self.assertRaises(ValueError, msg="msg"):
   |              ^^^^^^^^^^^^^^^^^
35 |             raise ValueError
   |
help: Replace `assertRaises` with `pytest.raises`

PT027 Use `pytest.raises` instead of unittest-style `assertRaises`
  --> PT027_0.py:37:14
   |
35 |             raise ValueError
36 |
37 |         with self.assertRaises(
   |              ^^^^^^^^^^^^^^^^^
38 |             # comment
39 |             ValueError
   |
help: Replace `assertRaises` with `pytest.raises`

PT027 Use `pytest.raises` instead of unittest-style `assertRaises`
  --> PT027_0.py:44:13
   |
43 |           with (
44 | /             self
45 | |             # comment
46 | |             .assertRaises(ValueError)
   | |_________________________^
47 |           ):
48 |               raise ValueError
   |
help: Replace `assertRaises` with `pytest.raises`
